# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YTZkNWQzMGQ2ZTMzMDY0OWRhMGE3ZDBiZjk1YmU2YTdkYWE3NDEzYWIzMjY2YTViYTc1YzNkNTAwM2IwZmFkMTZkYTE5NWQ3NWJiYmM1MzdkMDNmYTY3MWEwYTE0YWRlYTcxM2JmNDIzMWUxYTM4MDkwNDVmNjU5ZmFiZmM4YzI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
